sudo: required

language: php

php: '5.5'

services:
  - docker

#env:
#  DOCKER_COMPOSE_VERSION: 1.10.0

install:
  # - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip install docker-compose
  - pwd
  - ls -lah
  - docker-compose -v
  - wget https://raw.githubusercontent.com/Erdiko/docker/master/php/scripts/composer.sh
  - chmod 770 composer.sh
  - ./composer.sh
  - ls -lah
  - composer update
  - docker-compose up -d
  - docker-compose ps

before_script:
  - sleep 3
  - chmod 770 scripts/*.sh
  - docker exec erdiko_users_php /code/scripts/install-db.sh

script:
  - echo "$TRAVIS_BRANCH"
  - docker version
  - cat /etc/*-release
  - telnet 172.17.0.1 3301
  - docker inspect erdiko_users_db
  - docker exec erdiko_users_php /code/scripts/travis-debug.sh
  - netstat -tulpn
  - sudo docker exec erdiko_users_php /code/scripts/ci-tests.sh

notifications:
  email:
    - john@arroyolabs.com 
