version: '2.1'

services:
  data:
    image: busybox
    volumes:
      - ./:/code
      - ./composer-dev.json:/code/composer.json
      - ../authenticate:/authenticate
      - ../authorize:/authorize
      - ../users:/users

  webserver:
    extends:
      file: ./docker/nginx/docker-compose.yml
      service: webserver
    container_name: erdiko_users_web
    volumes_from: [data]

  php:
    container_name: erdiko_users_php
    env_file: ./docker/environment.env
    image: erdiko/php-fpm:latest
    volumes_from: [data]

  db:
    extends:
      file: ./docker/mysql/docker-compose.yml
      service: db
    container_name: erdiko_users_db
    ports:
      - "3301:3306"

  angular:
    image: erdiko/angular:latest
    container_name: erdiko_users_angular
    volumes_from: [data]
    env_file: ./docker/angular/environment.env
    volumes:
      - ../ngx-user-admin/:/ngx-user-admin
    entrypoint:
      - tail
      - -f
      - /dev/null
    ports:
      - "4200:4200"
