version: '2.1'

services:

  webserver:
    image: erdiko/nginx:latest
    container_name: erdiko_users_web
    ports:
      - "8088:80"
      - "80:80"

  php:
    container_name: erdiko_users_php
    env_file: ./docker/environment.env
    image: erdiko/php-fpm:latest

  db:
    extends:
      file: ./docker/mysql/docker-compose.yml
      service: db
    container_name: erdiko_users_db
    ports:
      - "3301:3306"

  protractor:
    extends:
      file: ./docker/protractor/docker-compose.yml
      service: protractor
    container_name: erdiko_users_protractor
    entrypoint:
      - tail
      - -f
      - /dev/null
