version: '2.1'

services:

  webserver:
    image: erdiko/nginx:latest
    container_name: erdiko_users_web

  php:
    container_name: erdiko_users_php
    env_file: ./docker/environment.env
    image: erdiko/php-fpm:latest

  db:
    extends:
      file: ./docker/mysql/docker-compose.yml
      service: db
    container_name: erdiko_users_db
    ports:
      - "3301:3306"
