version: '2.1'

services:

  webserver:
    extends:
      file: ./docker/nginx/docker-compose.yml
      service: webserver
    container_name: erdiko_users_web
    ports:
      - "80:80"

  php:
    container_name: erdiko_users_php
    env_file: ./docker/environment.env
    image: erdiko/php-fpm:latest
    extra_hosts:
      - "docker.local:172.17.0.1"

  db:
    extends:
      file: ./docker/mysql/docker-compose.yml
      service: db
    container_name: erdiko_users_db
    ports:
      - "3301:3306"
