version: '2.1'

services:
  data:
    image: busybox
    volumes:
      - ./:/code
      - ../authenticate:/authenticate
      - ../authorize:/authorize
      - ../users:/users

  webserver:
    extends:
      file: ./docker/nginx/docker-compose.yml
      service: webserver
    container_name: erdiko_users_web
    volumes_from: [data]
    ports:
      - "8088:80"

  php:
    container_name: erdiko_users_php
    env_file: ./docker/environment.env
    image: erdiko/php-fpm:latest
    volumes_from: [data]
    extra_hosts:
      - "docker.local:172.17.0.1"

  db:
    extends:
      file: ./docker/mysql/docker-compose.yml
      service: db
    container_name: erdiko_users_db
    ports:
      - "3301:3306"

  angular:
    extends:
      file: ./docker/node/docker-compose.yml
      service: node
    container_name: erdiko_users_angular
    volumes_from: [data]
